name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shell:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: ./test.sh

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install Zsh
        run: sudo apt-get update && sudo apt-get install --yes zsh
      - run: ./test.sh
