name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shell:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install Zsh
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --yes zsh
      - run: ./test.sh
